---
-
  name: Update system
  hosts: all

  tasks:
    - name: dpkg configure
      shell: sudo dpkg --configure -a
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
    - name: Update all packages 
      apt:
        upgrade: dist
    - name: Installing list of packages
      apt:
        pkg:
        - git
        - net-tools
        - vim
      # Download the folder from github
    - name:  Downloading ynh repo from github...
      shell: git clone https://github.com/sohaib1khan/Yunohost_install.git
      # Copy sudo script to home directory
    - name: copying sudo fix script
      copy:
        src: ./../sudo_error_fix
        dest: /usr/bin/
    # I have seen ths on a freshly installed bare minimum debian 11 where sudo was not installed. So i have added a script will fix the issue on a fedora or debian machine.
    - name: checking if sudo is installed
      shell: ./usr/bin/sudo_error_fix




