---
-
  name: Update system
  hosts: all

  tasks:
    - name: dpkg configure
      shell: sudo dpkg --configure -a
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
    - name: Update all packages 
      apt:
        upgrade: dist
    - name: Installing list of packages
      apt:
        pkg:
        - git
        - net-tools
        - vim
        - tree
      # Download the folder from github
    - name: cloning repo
      ansible.builtin.include_tasks: ./tasks/clone_repo.yaml
      # Copy sudo script to home directory
      # I have seen ths on a freshly installed bare minimum debian 11 where sudo was not installed. So i have added a script will fix the issue on a fedora or debian machine.
    - name: copying sudo fix script to /tmp directory 
      copy:
        src: ./../sudo_error_fix
        dest: /tmp/
    




