#!/bin/bash

# Update the system
sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt autoclean -y

# Install dependencies
sudo apt install curl gnupg2 ca-certificates lsb-release -y

# one script install

curl https://raw.githubusercontent.com/YunoHost/install_script/main/testing | bash


# Final cleanup
sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt autoclean -y


######################################################################################################
# NOTE: the below can be removed on the next version...

 # curl https://install.yunohost.org/switchtoTesting | bash