#!/bin/bash

# Update the system
sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt autoclean -y

# Install dependencies
sudo apt install curl gnupg2 ca-certificates lsb-release -y

# Import Yunohost GPG key
curl https://install.yunohost.org/public.key | sudo apt-key add -

# Add Yunohost repository
echo "deb https://install.yunohost.org/deb stable main" | sudo tee /etc/apt/sources.list.d/yunohost.list

# Update the system
sudo apt update

# Install Yunohost
sudo apt install yunohost -y

# Final cleanup
sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt autoclean -y


######################################################################################################
# NOTE: the below can be removed on the next version...

 curl https://install.yunohost.org/switchtoTesting | bash